create table if not exists public.transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  merchant text not null,
  category text not null,
  amount numeric(12, 2) not null check (amount >= 0),
  type text not null check (type in ('expense', 'income')),
  date timestamptz not null default now(),
  color text not null default '#a998c9',
  created_at timestamptz not null default now()
);

create index if not exists transactions_user_date_idx on public.transactions (user_id, date desc);
alter table public.transactions enable row level security;

create policy "Users can view their own transactions" on public.transactions for select using (auth.uid() = user_id);
create policy "Users can create their own transactions" on public.transactions for insert with check (auth.uid() = user_id);
create policy "Users can update their own transactions" on public.transactions for update using (auth.uid() = user_id);
create policy "Users can delete their own transactions" on public.transactions for delete using (auth.uid() = user_id);

create table if not exists public.budgets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  category text not null,
  monthly_limit numeric(12, 2) not null check (monthly_limit >= 0),
  month date not null,
  created_at timestamptz not null default now(),
  unique (user_id, category, month)
);

create table if not exists public.goals (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  target_amount numeric(12, 2) not null check (target_amount > 0),
  current_amount numeric(12, 2) not null default 0 check (current_amount >= 0),
  target_date date,
  color text not null default '#7771ee',
  created_at timestamptz not null default now()
);

create table if not exists public.categories (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  name text not null,
  color text not null default '#a998c9',
  created_at timestamptz not null default now(),
  unique (user_id, name)
);

create table if not exists public.recurring_transactions (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  merchant text not null,
  category text not null,
  amount numeric(12, 2) not null check (amount >= 0),
  type text not null check (type in ('expense', 'income')),
  frequency text not null check (frequency in ('weekly', 'monthly', 'yearly')),
  next_date date not null,
  active boolean not null default true,
  created_at timestamptz not null default now()
);

alter table public.budgets enable row level security;
alter table public.goals enable row level security;
alter table public.categories enable row level security;
alter table public.recurring_transactions enable row level security;

create policy "Users manage their own budgets" on public.budgets for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage their own goals" on public.goals for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage their own categories" on public.categories for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
create policy "Users manage their own recurring transactions" on public.recurring_transactions for all using (auth.uid() = user_id) with check (auth.uid() = user_id);
